/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as WorkspaceInactiveRouteImport } from './routes/workspace-inactive'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AdminWorkspacesIndexRouteImport } from './routes/admin.workspaces.index'
import { Route as AdminWorkspacesWorkspaceIdRouteImport } from './routes/admin.workspaces.$workspaceId'
import { Route as AdminWorkspacesNewRouteImport } from './routes/admin.workspaces.new'
import { Route as AppCustomersIndexRouteImport } from './routes/app.customers.index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app.customers.$customerId'
import { Route as AppFinancePaymentsRouteImport } from './routes/app.finance.payments'
import { Route as AppLeadsIndexRouteImport } from './routes/app.leads.index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/app.leads.$leadId'
import { Route as AppLeadsPipelineRouteImport } from './routes/app.leads.pipeline'
import { Route as AppPropertiesIndexRouteImport } from './routes/app.properties.index'
import { Route as AppPropertiesPropertyIdRouteImport } from './routes/app.properties.$propertyId'
import { Route as AppFinanceInvoicesIndexRouteImport } from './routes/app.finance.invoices.index'
import { Route as AppFinanceInvoicesInvoiceIdRouteImport } from './routes/app.finance.invoices.$invoiceId'
import { Route as AppFinanceInvoicesNewRouteImport } from './routes/app.finance.invoices.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceInactiveRoute = WorkspaceInactiveRouteImport.update({
  id: '/workspace-inactive',
  path: '/workspace-inactive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AdminWorkspacesIndexRoute = AdminWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesWorkspaceIdRoute =
  AdminWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWorkspacesNewRoute = AdminWorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => AdminRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePaymentsRoute = AppFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsPipelineRoute = AppLeadsPipelineRouteImport.update({
  id: '/leads/pipeline',
  path: '/leads/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesPropertyIdRoute = AppPropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesIndexRoute = AppFinanceInvoicesIndexRouteImport.update({
  id: '/finance/invoices/',
  path: '/finance/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesInvoiceIdRoute =
  AppFinanceInvoicesInvoiceIdRouteImport.update({
    id: '/finance/invoices/$invoiceId',
    path: '/finance/invoices/$invoiceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceInvoicesNewRoute = AppFinanceInvoicesNewRouteImport.update({
  id: '/finance/invoices/new',
  path: '/finance/invoices/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/setup': typeof SetupRoute
  '/workspace-inactive': typeof WorkspaceInactiveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdRoute
  '/admin/workspaces/new': typeof AdminWorkspacesNewRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/finance/payments': typeof AppFinancePaymentsRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads/pipeline': typeof AppLeadsPipelineRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/finance/invoices/$invoiceId': typeof AppFinanceInvoicesInvoiceIdRoute
  '/app/finance/invoices/new': typeof AppFinanceInvoicesNewRoute
  '/app/finance/invoices/': typeof AppFinanceInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/setup': typeof SetupRoute
  '/workspace-inactive': typeof WorkspaceInactiveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdRoute
  '/admin/workspaces/new': typeof AdminWorkspacesNewRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/finance/payments': typeof AppFinancePaymentsRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads/pipeline': typeof AppLeadsPipelineRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/admin/workspaces': typeof AdminWorkspacesIndexRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/leads': typeof AppLeadsIndexRoute
  '/app/properties': typeof AppPropertiesIndexRoute
  '/app/finance/invoices/$invoiceId': typeof AppFinanceInvoicesInvoiceIdRoute
  '/app/finance/invoices/new': typeof AppFinanceInvoicesNewRoute
  '/app/finance/invoices': typeof AppFinanceInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/setup': typeof SetupRoute
  '/workspace-inactive': typeof WorkspaceInactiveRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdRoute
  '/admin/workspaces/new': typeof AdminWorkspacesNewRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/finance/payments': typeof AppFinancePaymentsRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads/pipeline': typeof AppLeadsPipelineRoute
  '/app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/finance/invoices/$invoiceId': typeof AppFinanceInvoicesInvoiceIdRoute
  '/app/finance/invoices/new': typeof AppFinanceInvoicesNewRoute
  '/app/finance/invoices/': typeof AppFinanceInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/session-expired'
    | '/setup'
    | '/workspace-inactive'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/app/calendar'
    | '/app/reports'
    | '/app/settings'
    | '/app/tasks'
    | '/admin/'
    | '/app/'
    | '/admin/workspaces/$workspaceId'
    | '/admin/workspaces/new'
    | '/app/customers/$customerId'
    | '/app/finance/payments'
    | '/app/leads/$leadId'
    | '/app/leads/pipeline'
    | '/app/properties/$propertyId'
    | '/admin/workspaces/'
    | '/app/customers/'
    | '/app/leads/'
    | '/app/properties/'
    | '/app/finance/invoices/$invoiceId'
    | '/app/finance/invoices/new'
    | '/app/finance/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/session-expired'
    | '/setup'
    | '/workspace-inactive'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/app/calendar'
    | '/app/reports'
    | '/app/settings'
    | '/app/tasks'
    | '/admin'
    | '/app'
    | '/admin/workspaces/$workspaceId'
    | '/admin/workspaces/new'
    | '/app/customers/$customerId'
    | '/app/finance/payments'
    | '/app/leads/$leadId'
    | '/app/leads/pipeline'
    | '/app/properties/$propertyId'
    | '/admin/workspaces'
    | '/app/customers'
    | '/app/leads'
    | '/app/properties'
    | '/app/finance/invoices/$invoiceId'
    | '/app/finance/invoices/new'
    | '/app/finance/invoices'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/session-expired'
    | '/setup'
    | '/workspace-inactive'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/app/calendar'
    | '/app/reports'
    | '/app/settings'
    | '/app/tasks'
    | '/admin/'
    | '/app/'
    | '/admin/workspaces/$workspaceId'
    | '/admin/workspaces/new'
    | '/app/customers/$customerId'
    | '/app/finance/payments'
    | '/app/leads/$leadId'
    | '/app/leads/pipeline'
    | '/app/properties/$propertyId'
    | '/admin/workspaces/'
    | '/app/customers/'
    | '/app/leads/'
    | '/app/properties/'
    | '/app/finance/invoices/$invoiceId'
    | '/app/finance/invoices/new'
    | '/app/finance/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SetupRoute: typeof SetupRoute
  WorkspaceInactiveRoute: typeof WorkspaceInactiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-inactive': {
      id: '/workspace-inactive'
      path: '/workspace-inactive'
      fullPath: '/workspace-inactive'
      preLoaderRoute: typeof WorkspaceInactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/workspaces/': {
      id: '/admin/workspaces/'
      path: '/workspaces'
      fullPath: '/admin/workspaces/'
      preLoaderRoute: typeof AdminWorkspacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces/$workspaceId': {
      id: '/admin/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/admin/workspaces/$workspaceId'
      preLoaderRoute: typeof AdminWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces/new': {
      id: '/admin/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/admin/workspaces/new'
      preLoaderRoute: typeof AdminWorkspacesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/payments': {
      id: '/app/finance/payments'
      path: '/finance/payments'
      fullPath: '/app/finance/payments'
      preLoaderRoute: typeof AppFinancePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/': {
      id: '/app/leads/'
      path: '/leads'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/$leadId': {
      id: '/app/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/app/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/pipeline': {
      id: '/app/leads/pipeline'
      path: '/leads/pipeline'
      fullPath: '/app/leads/pipeline'
      preLoaderRoute: typeof AppLeadsPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/': {
      id: '/app/properties/'
      path: '/properties'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/$propertyId': {
      id: '/app/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/app/properties/$propertyId'
      preLoaderRoute: typeof AppPropertiesPropertyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/invoices/': {
      id: '/app/finance/invoices/'
      path: '/finance/invoices'
      fullPath: '/app/finance/invoices/'
      preLoaderRoute: typeof AppFinanceInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/invoices/$invoiceId': {
      id: '/app/finance/invoices/$invoiceId'
      path: '/finance/invoices/$invoiceId'
      fullPath: '/app/finance/invoices/$invoiceId'
      preLoaderRoute: typeof AppFinanceInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance/invoices/new': {
      id: '/app/finance/invoices/new'
      path: '/finance/invoices/new'
      fullPath: '/app/finance/invoices/new'
      preLoaderRoute: typeof AppFinanceInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWorkspacesWorkspaceIdRoute: typeof AdminWorkspacesWorkspaceIdRoute
  AdminWorkspacesNewRoute: typeof AdminWorkspacesNewRoute
  AdminWorkspacesIndexRoute: typeof AdminWorkspacesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminWorkspacesWorkspaceIdRoute: AdminWorkspacesWorkspaceIdRoute,
  AdminWorkspacesNewRoute: AdminWorkspacesNewRoute,
  AdminWorkspacesIndexRoute: AdminWorkspacesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppFinancePaymentsRoute: typeof AppFinancePaymentsRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppLeadsPipelineRoute: typeof AppLeadsPipelineRoute
  AppPropertiesPropertyIdRoute: typeof AppPropertiesPropertyIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
  AppFinanceInvoicesInvoiceIdRoute: typeof AppFinanceInvoicesInvoiceIdRoute
  AppFinanceInvoicesNewRoute: typeof AppFinanceInvoicesNewRoute
  AppFinanceInvoicesIndexRoute: typeof AppFinanceInvoicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppFinancePaymentsRoute: AppFinancePaymentsRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppLeadsPipelineRoute: AppLeadsPipelineRoute,
  AppPropertiesPropertyIdRoute: AppPropertiesPropertyIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
  AppFinanceInvoicesInvoiceIdRoute: AppFinanceInvoicesInvoiceIdRoute,
  AppFinanceInvoicesNewRoute: AppFinanceInvoicesNewRoute,
  AppFinanceInvoicesIndexRoute: AppFinanceInvoicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SetupRoute: SetupRoute,
  WorkspaceInactiveRoute: WorkspaceInactiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
